name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.131.0"
          extended: true

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./public
